apiVersion: capabilities.3scale.net/v1beta1
kind: ActiveDoc
metadata:
  name: library-books-api
spec:
  providerAccountRef:
    name: tenant-secret
  activeDocOpenAPIRef:
    url: >-
      https://github.com/jeanNyil/3scale-gitops/blob/dev/3scale/base/openapis/library-books-api.yaml
  name: Operated ActiveDoc From URL
  productSystemName: library-books-api
  published: true