---
apiVersion: v1
kind: Secret
metadata:
  name: test-user-secret
stringData:
  password: openshift
type: Opaque
---
kind: DeveloperAccount
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: test-account
spec:
  orgName: Test
  providerAccountRef:
    name: tenant-secret
---
kind: DeveloperUser
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: test-user
spec:
  developerAccountRef:
    name: test-account
  email: testuser@example.com
  passwordCredentialsRef:
    name: test-user-secret
  providerAccountRef:
    name: tenant-secret
  role: admin
  username: testdeveloper
---
kind: Application
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: test-account-application
spec:
  accountCR:
    name: test-account
  applicationPlanName: v2-basic
  description: 'Test Account application for the Library Books API'
  name: Test Account App
  productCR:
    name: library-books-api