apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: library-books-api
spec:
  name: Library Books API
  systemName: library-books-api
  description: Manages a library books inventory
  providerAccountRef:
    name: tenant-secret
  deployment:
    apicastHosted:
      authentication:
        appKeyAppID:
          appID: app_id
          appKey: app_key
          credentials: headers
  mappingRules:
    - httpMethod: GET
      pattern: "/v1/books$"
      metricMethodRef: get-books-v1
      increment: 1
      last: false
  metrics:
    hits:
      friendlyName: Hits
      unit: hit
      description: Number of API hits
  methods:
    get-books-v1:
      friendlyName: getBooks-v1
      description: 'List All Books-v1'
  policies:
    - name: cors
      version: builtin
      configuration:
        allow_credentials: true
        allow_headers:
        - app_id
        - app_key
        allow_methods:
        - GET
        - OPTIONS
        allow_origin: "*"
      enabled: true
    - name: logging
      version: builtin
      configuration:
        condition:
          combine_op: and
        enable_access_logs: true
        custom_logging: '[{{time_local}}] [source ip: "{{headers[''x-forwarded-for'']}}"] [local: {{host}}:{{server_port}}] [remote: {{remote_addr}}:{{remote_port}}] [app_id: "{{credentials.app_id}}"] [request: "{{request}}" to service [service id: {{service.id}}, service name: {{service.system_name}}] - status: {{status}} - body bytes sent: {{body_bytes_sent}} - request time: {{request_time}} - post action impact: {{post_action_impact}}]'
      enabled: true
    - name: apicast
      version: builtin
      configuration: {}
      enabled: true
  applicationPlans:
    v1-basic:
      name: v1-basic
      appsRequireApproval: true
      trialPeriod: 0
      setupFee: '0.00'
      costMonth: '0.00'
      published: true
      limits:
      - period: minute
        value: 5
        metricMethodRef:
          systemName: get-books-v1
    v1-premium:
      name: v1-premium
      appsRequireApproval: true
      trialPeriod: 0
      setupFee: '15.00'
      costMonth: '5.00'
      published: true
      pricingRules:
      - from: 1
        to: 200
        pricePerUnit: '0.05'
        metricMethodRef:
          systemName: get-books-v1
      - from: 201
        to: 10000
        pricePerUnit: '0.01'
        metricMethodRef:
          systemName: get-books-v1
      limits:
      - period: minute
        value: 1200
        metricMethodRef:
          systemName: get-books-v1
  backendUsages:
    books-api-v1-backend:
      path: "/v1"