apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: threescale-development-tenant
  namespace: threescale-development
spec:
  email: dev@example.openshift.com
  masterCredentialsRef:
    name: system-seed
    namespace: 3scale
  organizationName: development
  passwordCredentialsRef:
    name: tenant-admin-secret
    namespace: 3scale
  systemMasterUrl: 'https://master.apps.cluster-f6q45.f6q45.sandbox1573.opentlc.com'
  tenantSecretRef:
    name: tenant-secret
  username: admin