apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: threescale-production-tenant
  namespace: threescale-production
spec:
  email: prod@example.openshift.com
  masterCredentialsRef:
    name: system-seed
    namespace: 3scale-amp
  organizationName: production
  passwordCredentialsRef:
    name: tenant-admin-secret
    namespace: 3scale-amp
  systemMasterUrl: 'https://master.apps.cluster-9pmvg.9pmvg.sandbox3187.opentlc.com'
  tenantSecretRef:
    name: tenant-secret
  username: admin
