apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: threescale-development-tenant
  namespace: threescale-development
spec:
  email: dev@example.openshift.com
  masterCredentialsRef:
    name: system-seed
    namespace: 3scale-amp
  organizationName: development
  passwordCredentialsRef:
    name: tenant-admin-secret
    namespace: 3scale-amp
  systemMasterUrl: 'https://master.apps.cluster-8bcs7.8bcs7.sandbox2056.opentlc.com'
  tenantSecretRef:
    name: tenant-secret
  username: admin