apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: threescale-testing-tenant
  namespace: threescale-testing
spec:
  email: test@example.openshift.com
  masterCredentialsRef:
    name: system-seed
    namespace: 3scale-amp
  organizationName: testing
  passwordCredentialsRef:
    name: tenant-admin-secret
    namespace: 3scale-amp
  systemMasterUrl: 'https://master.apps.ocp4.jnyilimb.eu'
  tenantSecretRef:
    name: tenant-secret
  username: admin