apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threescale-test
spec:
  destination:
    namespace: threescale-testing
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 3scale/
    repoURL: https://github.com/jeanNyil/3scale-gitops.git
    targetRevision: test
  syncPolicy:
    # Disable the ApplyOutOfSyncOnly option to make sure the ProxyConfigPromote CR is always applied
    syncOptions:
    - ApplyOutOfSyncOnly=false