apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: library-books-api
spec:
  name: Library Books API
  systemName: library-books-api
  deployment:
    apicastHosted:
      authentication:
        oidc:
          issuerType: keycloak
          issuerEndpoint: https://threescale-zync:AtqmhxVM5WrPzHE1U7WwRFkWI7onL7Nn@sso.apps.cluster-tpbfg.tpbfg.sandbox318.opentlc.com/auth/realms/demo-prod