apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: library-books-api
spec:
  name: Library Books API
  deployment:
    apicastHosted:
      authentication:
        oidc:
          issuerType: keycloak
          issuerEndpoint: https://threescale-zync:6RVkFG7nxuNuP6T9JOdg0vK8v1GeJRit@sso-rhbk22.apps.ocp4.jnyilimb.eu/realms/demo-prod