apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: library-books-api
spec:
  name: Library Books API
  systemName: library-books-api
  deployment:
    apicastHosted:
      authentication:
        oidc:
          issuerType: keycloak
          issuerEndpoint: https://threescale-zync:j5Ds5veNHNt3SEbLgPYuIcg5EtP61thJ@sso.apps.ocp4.jnyilimb.eu/auth/realms/demo-dev
